name: Build and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Image and Run the build command
        run: |
          docker compose run --build --rm app bash -c "npm install && NODE_ENV=production npm run build"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/*
            pkg/*
